# Generated by Django 5.0.1 on 2024-03-06 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_cart_razorpay_order_id_cart_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_payment_status",
        ),
    ]
