# Generated by Django 5.0.1 on 2024-03-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_payment_paid_remove_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('EN', 'EveningNasta'), ('D', 'Dinner')], max_length=2),
        ),
    ]
